### ISSUE TITLE
(601) Fazer um protótipo de gráfico de linha que represente o sentimento da empresa ao longo do tempo

### ISSUE THREAD

**Issue by BugaM** [BugaM/Sentzer#10]

**Comment by edmsimplicio** [comment]
Mergeei isso na main, posso fechar essa task? ou quer que mude algo

![image](https://user-images.githubusercontent.com/63891357/229379588-ce11eea2-da85-413b-8d9e-aa8d4f17cbac.png)

**Comment by BugaM** [comment]
Por mim ta safe
