### ISSUE TITLE
(201) Construir o schema do banco de dados

### ISSUE THREAD

**Issue by BugaM** [BugaM/Sentzer#5]

**Comment by BugaM** [comment]
![Image](https://user-images.githubusercontent.com/70119219/229378725-c3208213-c6b4-405b-88ea-88fdedd01168.png)

**Comment by BugaM** [comment]
@Costa-SM @matheus-creator  precisamos de mais fields? @edmsimplicio precisamos adicionar uma connection de usuario?

**Comment by edmsimplicio** [comment]
usuario que vc diz é o usuario do twitter? se for acho que não.

**Comment by matheus-srm** [comment]
Acho que seria interessante colocar a empresa tbm (o @). Daí a gente pode dividir os tweets

**Comment by BugaM** [comment]
![Image](https://user-images.githubusercontent.com/70119219/230365605-f17a42cb-acb5-484a-8ae6-375258cf61ab.png)
